from __future__ import annotations

import hashlib
import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from ai_first.render import render_repository

FRAMEWORK = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("standalone", FRAMEWORK / "framework/standalone/check.py")
standalone = importlib.util.module_from_spec(spec)
spec.loader.exec_module(standalone)


class InterfaceTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        shutil.copytree(FRAMEWORK / "tests/fixtures/minimal", self.root, dirs_exist_ok=True)
        (self.root / "scripts").mkdir(exist_ok=True)
        render_repository(self.root, FRAMEWORK)

    def check(self):
        lock = json.loads((self.root / ".ai-first.lock").read_text())
        return standalone.verify_interface(self.root, lock)

    def test_version_and_profile_update_needs_no_native_checker_edit(self):
        native = self.root / "scripts/native.sh"
        native.write_text("#!/bin/sh\nset -eu\npython3 .ai-first/check.py\ntest -s docs/agent-harness.md\n")
        original = native.read_bytes()
        config = self.root / ".ai-first.toml"
        config.write_text(config.read_text().replace("1.7.0-dev", "1.7.1-dev").replace('"public-repository"]', '"public-repository", "verification"]'))
        with patch("ai_first.config.VERSION", "1.7.1-dev"):
            render_repository(self.root, FRAMEWORK)
        completed = subprocess.run(["sh", str(native)], cwd=self.root, text=True, capture_output=True)
        self.assertEqual(completed.returncode, 0, completed.stdout + completed.stderr)
        self.assertEqual(native.read_bytes(), original)

    def test_shared_assertions_survive_rehashed_outputs(self):
        for relative, old, new, expected in [
            ("AGENTS.md", "Generated by ai-first 1.7.0-dev", "Generated by ai-first stale", "generated boundary"),
            ("AGENTS.md", "### Capability Profile: vcs-jj", "### Capability Profile: wrong", "profile order"),
            ("docs/agent-harness.md", "### vcs-jj", "### wrong", "profile order"),
            ("docs/agent-harness.md", "## Interface", "## Wrong", "section order"),
            ("docs/agent-harness.md", "- Framework version: `1.7.0-dev`.", "- Framework version: `stale`.", "metadata"),
        ]:
            with self.subTest(relative=relative, expected=expected):
                render_repository(self.root, FRAMEWORK)
                path = self.root / relative
                path.write_text(path.read_text().replace(old, new))
                lock_path = self.root / ".ai-first.lock"
                lock = json.loads(lock_path.read_text())
                lock["outputs"][relative] = hashlib.sha256(path.read_bytes()).hexdigest()
                lock_path.write_text(json.dumps(lock))
                self.assertTrue(any(expected in message for message in self.check()), self.check())

    def test_missing_output_or_input_role_is_rejected(self):
        for group, key in [("outputs", "AGENTS.md"), ("repository_inputs", ".ai-first.toml")]:
            render_repository(self.root, FRAMEWORK)
            lock_path = self.root / ".ai-first.lock"
            lock = json.loads(lock_path.read_text())
            del lock[group][key]
            lock_path.write_text(json.dumps(lock))
            self.assertTrue(self.check())

    def test_product_gate_still_runs_after_shared_check(self):
        native = self.root / "scripts/native.sh"
        native.write_text("#!/bin/sh\nset -eu\npython3 .ai-first/check.py\ntest -f product-acceptance.txt\n")
        failed = subprocess.run(["sh", str(native)], cwd=self.root, capture_output=True)
        self.assertEqual(failed.returncode, 1)
        (self.root / "product-acceptance.txt").write_text("accepted")
        passed = subprocess.run(["sh", str(native)], cwd=self.root, capture_output=True)
        self.assertEqual(passed.returncode, 0, passed.stdout + passed.stderr)
