from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .config import Config, ConfigError, load_config, path_within


class DriftError(RuntimeError):
    pass


@dataclass(frozen=True)
class Rendered:
    outputs: dict[str, bytes]
    lock: bytes


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _read(path: Path, label: str) -> bytes:
    try:
        return path.read_bytes()
    except FileNotFoundError as error:
        raise ConfigError(f"missing {label}") from error


def _text(data: bytes, label: str) -> str:
    try:
        value = data.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ConfigError(f"{label} must be UTF-8") from error
    return value.strip()


def _headings(fragment: str) -> list[str]:
    return [line for line in fragment.splitlines() if line.startswith("## ")]


def _validate_overlay(fragment: str, expected: list[str], label: str) -> None:
    actual = _headings(fragment)
    if actual != expected:
        raise ConfigError(f"{label} headings must be {expected!r}")


def _validate_profile(fragment: str, label: str) -> None:
    if _headings(fragment):
        raise ConfigError(f"{label} must not define level-two headings")
    if not fragment.startswith("### "):
        raise ConfigError(f"{label} must start with a level-three heading")


def _generated_header(version: str) -> str:
    return (
        "<!-- Generated by ai-first "
        f"{version}. Edit .ai-first.toml or .ai-first/overlays/, then render. -->"
    )


def _join(parts: list[str]) -> bytes:
    return ("\n\n".join(part.strip() for part in parts if part.strip()) + "\n").encode(
        "utf-8"
    )


def _aggregate_digest(entries: dict[str, str]) -> str:
    canonical = json.dumps(entries, sort_keys=True, separators=(",", ":")).encode()
    return _digest(canonical)


def build(repo_root: Path, framework_root: Path) -> Rendered:
    config = load_config(repo_root)
    framework = framework_root.resolve()

    framework_inputs: dict[str, bytes] = {}
    repository_inputs: dict[str, bytes] = {
        ".ai-first.toml": _read(config.config_path, ".ai-first.toml")
    }

    def framework_text(relative: str) -> str:
        data = _read(framework / relative, relative)
        framework_inputs[relative] = data
        return _text(data, relative)

    def repository_text(relative: str) -> str:
        data = _read(config.repo_root / relative, relative)
        repository_inputs[relative] = data
        return _text(data, relative)

    agents_first = repository_text(config.overlay.agents_first_read)
    agents_project = repository_text(config.overlay.agents_project)
    harness_project = repository_text(config.overlay.harness_project)
    _validate_overlay(agents_first, ["## First Read"], "agents_first_read")
    _validate_overlay(agents_project, ["## Repository Overlay"], "agents_project")
    _validate_overlay(
        harness_project,
        ["## Project Overlay", "## Related Documents"],
        "harness_project",
    )
    if any(line.startswith("#") for line in config.project.objective.splitlines()):
        raise ConfigError("project.objective must not define Markdown headings")

    agents_core = framework_text("framework/core/AGENTS.md")
    harness_core = framework_text("framework/core/agent-harness.md")
    _validate_overlay(agents_core, ["## AI-first Core Contract"], "core AGENTS")

    agents_profiles: list[str] = []
    harness_profiles: list[str] = []
    for profile in config.profiles:
        agents_fragment = framework_text(
            f"framework/profiles/{profile}/AGENTS.md"
        )
        harness_fragment = framework_text(
            f"framework/profiles/{profile}/agent-harness.md"
        )
        _validate_profile(agents_fragment, f"profile {profile} AGENTS")
        _validate_profile(harness_fragment, f"profile {profile} harness")
        agents_profiles.append(agents_fragment)
        harness_profiles.append(harness_fragment)

    standalone_relative = "framework/standalone/check.py"
    standalone = _read(framework / standalone_relative, standalone_relative)
    framework_inputs[standalone_relative] = standalone
    generator_root = framework / "src" / "ai_first"
    for path in sorted(generator_root.glob("*.py")):
        relative = path.relative_to(framework).as_posix()
        framework_inputs[relative] = _read(path, relative)

    header = _generated_header(config.framework_version)
    agents = _join(
        [
            header,
            f"# {config.project.name} Agent Guide",
            (
                "이 파일은 AI-first core, capability profile과 repository overlay를 "
                "합성한 tracked bootstrap map이다."
            ),
            agents_first,
            agents_core,
            *agents_profiles,
            agents_project,
        ]
    )
    harness_interface = "\n".join(
        [
            "## Interface",
            "",
            "- Structure ID: `ai-first-harness-v1`.",
            f"- Framework version: `{config.framework_version}`.",
            f"- Project: `{config.project.name}`.",
            f"- Publication class: `{config.project.publication_class}`.",
            "- Generated drift check: `python3 .ai-first/check.py`.",
        ]
    )
    project_objective = "\n".join(
        ["## Project Objective", "", config.project.objective]
    )
    capability_profiles = _join(
        ["## Capability Profiles", *harness_profiles]
    ).decode("utf-8").strip()
    harness = _join(
        [
            header,
            "# Agent Harness",
            harness_interface,
            project_objective,
            harness_core,
            capability_profiles,
            harness_project,
        ]
    )

    outputs = {
        config.output.agents: agents,
        config.output.harness: harness,
        config.output.standalone_check: standalone,
    }
    framework_hashes = {
        path: _digest(data) for path, data in sorted(framework_inputs.items())
    }
    repository_hashes = {
        path: _digest(data) for path, data in sorted(repository_inputs.items())
    }
    output_hashes = {
        path: _digest(data) for path, data in sorted(outputs.items())
    }
    lock = {
        "schema_version": 1,
        "framework": {
            "version": config.framework_version,
            "source_kind": config.source_kind,
            "digest": _aggregate_digest(framework_hashes),
        },
        "profiles": list(config.profiles),
        "framework_inputs": framework_hashes,
        "repository_inputs": repository_hashes,
        "outputs": output_hashes,
    }
    lock_bytes = (
        json.dumps(lock, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    return Rendered(outputs=outputs, lock=lock_bytes)


def _atomic_write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as handle:
        handle.write(data)
        temporary = Path(handle.name)
    os.replace(temporary, path)


def render_repository(repo_root: Path, framework_root: Path) -> list[str]:
    config = load_config(repo_root)
    rendered = build(repo_root, framework_root)
    changed: list[str] = []
    for relative, data in rendered.outputs.items():
        path = path_within(config.repo_root, relative, f"output {relative}")
        if not path.is_file() or path.read_bytes() != data:
            _atomic_write(path, data)
            changed.append(relative)
    lock_path = path_within(
        config.repo_root,
        config.output.lock,
        f"output {config.output.lock}",
    )
    if not lock_path.is_file() or lock_path.read_bytes() != rendered.lock:
        _atomic_write(lock_path, rendered.lock)
        changed.append(config.output.lock)
    return sorted(changed)


def check_repository(repo_root: Path, framework_root: Path) -> None:
    config = load_config(repo_root)
    rendered = build(repo_root, framework_root)
    failures: list[str] = []
    for relative, expected in rendered.outputs.items():
        path = path_within(config.repo_root, relative, f"output {relative}")
        if not path.is_file():
            failures.append(f"missing {relative}")
        elif path.read_bytes() != expected:
            failures.append(f"drifted {relative}")
    lock_path = path_within(
        config.repo_root,
        config.output.lock,
        f"output {config.output.lock}",
    )
    if not lock_path.is_file():
        failures.append(f"missing {config.output.lock}")
    elif lock_path.read_bytes() != rendered.lock:
        failures.append(f"drifted {config.output.lock}")
    if failures:
        raise DriftError("; ".join(failures))
