#!/bin/sh
# shellcheck disable=SC2016
set -eu

repo_root=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

fail() {
  printf 'agent harness interface check failed: %s\n' "$*" >&2
  exit 1
}

for required_file in \
  AGENTS.md \
  CONTRIBUTING.md \
  LICENSE \
  README.md \
  SECURITY.md \
  docs/AI_FIRST_CHARTER.md \
  docs/ARCHITECTURE.md \
  docs/agent-harness.md \
  docs/HANDOFF.md \
  docs/status.md \
  docs/roadmap.md \
  docs/completed-milestones.md \
  docs/PUBLICATION.md \
  docs/REPO_MANIFEST.yaml \
  docs/todo-bootstrap-core/spec.md \
  docs/todo-bootstrap-core/open-questions.md \
  docs/todo-public-foundation/spec.md \
  docs/todo-public-foundation/open-questions.md; do
  [ -s "$required_file" ] || fail "missing or empty $required_file"
done

expected_agents_headings=$(cat <<'HEADINGS'
## First Read
## AI-first Core Contract
## Repository Overlay
HEADINGS
)
actual_agents_headings=$(sed -n 's/^\(## .*\)$/\1/p' AGENTS.md)
[ "$actual_agents_headings" = "$expected_agents_headings" ] ||
  fail "AGENTS.md section order differs from the bootstrap map"

grep -Fq -- '<!-- Generated by ai-first 0.1.0-dev.' AGENTS.md ||
  fail "AGENTS.md generated boundary is missing"
grep -Fq -- '<!-- Generated by ai-first 0.1.0-dev.' docs/agent-harness.md ||
  fail "docs/agent-harness.md generated boundary is missing"

for required_line in \
  '- Structure ID: `ai-first-harness-v1`.' \
  '- Framework version: `0.1.0-dev`.' \
  '- Project: `ai-first`.' \
  '- Publication class: `public`.' \
  '- Generated drift check: `python3 .ai-first/check.py`.'; do
  grep -Fq -- "$required_line" docs/agent-harness.md ||
    fail "docs/agent-harness.md is missing: $required_line"
done

expected_harness_headings=$(cat <<'HEADINGS'
## Interface
## Project Objective
## Core Operating Contract
## Execution Loop
## Verification And Evidence
## Escalation
## VCS And Publish
## Harness Evaluation And Improvement
## Capability Profiles
## Project Overlay
## Related Documents
HEADINGS
)
actual_harness_headings=$(sed -n 's/^\(## .*\)$/\1/p' docs/agent-harness.md)
[ "$actual_harness_headings" = "$expected_harness_headings" ] ||
  fail "docs/agent-harness.md section order differs from ai-first-harness-v1"

expected_profile_headings=$(cat <<'HEADINGS'
### Capability Profile: vcs-jj
### Capability Profile: public-repository
HEADINGS
)
actual_profile_headings=$(sed -n 's/^\(### Capability Profile: .*\)$/\1/p' AGENTS.md)
[ "$actual_profile_headings" = "$expected_profile_headings" ] ||
  fail "AGENTS.md capability profile order differs from .ai-first.toml"

expected_harness_profiles=$(cat <<'HEADINGS'
### vcs-jj
### public-repository
HEADINGS
)
actual_harness_profiles=$(sed -n 's/^\(### .*\)$/\1/p' docs/agent-harness.md)
[ "$actual_harness_profiles" = "$expected_harness_profiles" ] ||
  fail "docs/agent-harness.md capability profile order differs from .ai-first.toml"

grep -Fq -- 'AI는 command-only assistant가 아니라' AGENTS.md ||
  fail "AI-first identity is missing from AGENTS.md"
grep -Fq -- '방향지시자, 동반자와 project manager' docs/AI_FIRST_CHARTER.md ||
  fail "human role is missing from the charter"
grep -Fq -- '전용 migration workspace' docs/ARCHITECTURE.md ||
  fail "migration workspace boundary is missing"
grep -Fq -- '"source_kind": "development"' .ai-first.lock ||
  fail "development source kind is missing from .ai-first.lock"

printf 'agent harness interface check passed\n'
